version: "3.9"

services:
  lab4_postgres:
    image: postgres:14-alpine
    container_name: lab4_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: baza_lab4
    volumes:
      - lab4_postgres_data:/var/lib/postgresql/data

volumes:
  lab4_postgres_data:
    driver: local
